### PR TITLE
tidied up github link text

### PR DESCRIPTION
**Pull request by davehodg**

### CODE REVIEW

**Comment by xsawyerx** [comment]
Why name it to this? It's a PR guide, it's now about how to use Git properly. _Properly_ here would have to be subjective.

**Comment by paultcochrane** [comment]
I agree with Sawyer. For a guide about how to use Git properly, one should read e.g. http://git-scm.com/book.

+1 for rename back to PR guide.

**Comment by davehodg** [comment]
It needs a mention of git! It wasn't clear to me that a git tutorial was at the end of the link!

**Comment by xsawyerx** [comment]
It's not exactly a Git tutorial. It's a Github PR tutorial. I think the name was fully descriptive of what it is.

I just thought now about renaming it to "Github Git PR tutorial" or some other assortment, but really, the best description I can come up with is just "Github PR tutorial".

**Comment by neilb** [comment]
I think "Github PR tutorial" is just fine.

**Pull request merged**
